import initSmoothScroll from "./modules/smooth-scroll.js";
import initAnimationScroll from "./modules/animation-scroll.js";
import initAccordion from "./modules/accordion.js";
import initTabNav from "./modules/tab-nav.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initNumbersAnimation from "./modules/numbers-animation.js";
import initTime from "./modules/time.js";
initSmoothScroll();
initAnimationScroll();
initAccordion();
initTabNav();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initNumbersAnimation();
initTime();
